global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: llama
    metrics_path: /metrics
    static_configs:
      - targets: ["llama:8000"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

